package com.mateuszholik.designsystem.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF3E691A)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFBEF291)
internal val md_theme_light_onPrimaryContainer = Color(0xFF0C2000)
internal val md_theme_light_secondary = Color(0xFF56624B)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFDAE7C9)
internal val md_theme_light_onSecondaryContainer = Color(0xFF141E0C)
internal val md_theme_light_tertiary = Color(0xFF386665)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFBBECEA)
internal val md_theme_light_onTertiaryContainer = Color(0xFF00201F)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFDFDF5)
internal val md_theme_light_onBackground = Color(0xFF1A1C18)
internal val md_theme_light_surface = Color(0xFFFDFDF5)
internal val md_theme_light_onSurface = Color(0xFF1A1C18)
internal val md_theme_light_surfaceVariant = Color(0xFFE0E4D6)
internal val md_theme_light_onSurfaceVariant = Color(0xFF44483E)
internal val md_theme_light_outline = Color(0xFF74796D)
internal val md_theme_light_inverseOnSurface = Color(0xFFF1F1EA)
internal val md_theme_light_inverseSurface = Color(0xFF2F312C)
internal val md_theme_light_inversePrimary = Color(0xFFA2D578)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF3E691A)
internal val md_theme_light_outlineVariant = Color(0xFFC4C8BA)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFFA2D578)
internal val md_theme_dark_onPrimary = Color(0xFF193800)
internal val md_theme_dark_primaryContainer = Color(0xFF275000)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFBEF291)
internal val md_theme_dark_secondary = Color(0xFFBECBAE)
internal val md_theme_dark_onSecondary = Color(0xFF29341F)
internal val md_theme_dark_secondaryContainer = Color(0xFF3F4A34)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFDAE7C9)
internal val md_theme_dark_tertiary = Color(0xFFA0CFCD)
internal val md_theme_dark_onTertiary = Color(0xFF003736)
internal val md_theme_dark_tertiaryContainer = Color(0xFF1E4E4D)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFBBECEA)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF1A1C18)
internal val md_theme_dark_onBackground = Color(0xFFE3E3DC)
internal val md_theme_dark_surface = Color(0xFF1A1C18)
internal val md_theme_dark_onSurface = Color(0xFFE3E3DC)
internal val md_theme_dark_surfaceVariant = Color(0xFF44483E)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC4C8BA)
internal val md_theme_dark_outline = Color(0xFF8E9286)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
internal val md_theme_dark_inverseSurface = Color(0xFFE3E3DC)
internal val md_theme_dark_inversePrimary = Color(0xFF3E691A)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFFA2D578)
internal val md_theme_dark_outlineVariant = Color(0xFF44483E)
internal val md_theme_dark_scrim = Color(0xFF000000)

internal val seed = Color(0xFF3E691A)
